version = "3.11.0"
runner.dialect = scala3
maxColumn = 100

align.preset = none
assumeStandardLibraryStripMargin = true
danglingParentheses.preset = true
docstrings.style = Asterisk
newlines.source = fold
fileOverride {
  "glob:**/*Endpoints.scala" {
    newlines.selectChains.style = unfold
  }
}
rewrite.rules = [
  SortImports,
  RedundantBraces,
  RedundantParens
]
rewrite.trailingCommas.style = multiple
